POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlcjIiLCJpZCI6IjY0MzdlMTJhOTY5MDdkN2UxMTYzYTJhOSIsImlhdCI6MTY4MTM4Mzc0OSwiZXhwIjoxNjgxMzkwOTQ5fQ.XIlstf9C7lQdebZYhxEbxgiUeykBWkwpPwJHF2TR7xc

{ "title": "first blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlcjIiLCJpZCI6IjY0MzdlMTJhOTY5MDdkN2UxMTYzYTJhOSIsImlhdCI6MTY4MTM4Mzc0OSwiZXhwIjoxNjgxMzkwOTQ5fQ.XIlstf9C7lQdebZYhxEbxgiUeykBWkwpPwJHF2TR7xc

{ "title": "second blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress2.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "third blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress3.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "fourth blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress3.fi",
  "likes": 1
}