POST http://localhost:3003/api/users/ HTTP/1.1 
content-type: application/json

{ "username": "superuser2",
  "name": "Matias Mäkynen",
  "password": "topsecret" 
}


###

POST http://localhost:3003/api/users/ HTTP/1.1 
content-type: application/json

{ "username": "superuser3",
  "name": "Paavo Väyrynen",
  "password": "topsecret2" 
}


###

POST http://localhost:3003/api/users/ HTTP/1.1 
content-type: application/json

{ 
  "name": "Matias Mäkynen",
  "password": "topsecret" 
}

###

POST http://localhost:3003/api/users/ HTTP/1.1 
content-type: application/json

{ 
  "username": "su",
  "name": "Matias Mäkynen",
  "password": "topsecret" 
}